### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by betabandido** [hashicorp/terraform-provider-null#45] opened 2020-08-10 11:34 UTC
### Terraform Version
Terraform v0.13.0-rc1
+ provider registry.terraform.io/hashicorp/aws v3.1.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/helm v1.2.4
+ provider registry.terraform.io/hashicorp/kubernetes v1.12.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/terraform-providers/gitlab v2.11.0

We use v0.13 as we need `depends_on` to work with modules (something that has been made available in v0.13).

### Affected Resource(s)
- null_resource

### Terraform Configuration Files
```hcl
resource "helm_release" "ingress" {
  count = var.ingress == null ? 0 : 1

  name             = "nginx-ingress"
  namespace        = "nginx-ingress"
  create_namespace = true
  repository       = "https://kubernetes-charts.storage.googleapis.com"
  chart            = "nginx-ingress"
  version          = "1.41.2"

  values = [
    <<-EOT
      # some YAML configuration
    EOT
  ]
}

resource "null_resource" "wait_for_elb" {
  count = var.ingress == null ? 0 : 1

  triggers = {
    chart     = helm_release.ingress.0.metadata[0].chart
    name      = helm_release.ingress.0.metadata[0].name
    namespace = helm_release.ingress.0.metadata[0].namespace
    version   = helm_release.ingress.0.metadata[0].version
    values    = helm_release.ingress.0.metadata[0].values
  }

  provisioner "local-exec" {
    command = <<-EOT
      timeout 300 sh -c 'while true; do
        grep "elb.eu-west-1.amazonaws.com" <<<$(
          kubectl -n ${self.triggers.namespace} \
            get service ${self.triggers.name}-controller \
            -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"
          )
        if [ $? -eq 0 ]; then
          break
        else
          exit 1
        fi
        sleep 1
      done' || false
    EOT
  }
}
```

### Expected Behavior
The null_resource should have been triggered (as some values in the trigger block changed), and it should have waited until the Helm package was installed.

### Actual Behavior
Terraform gave the following error:

```
Error: Provider produced inconsistent final plan

When expanding the plan for module.cluster.null_resource.wait_for_elb[0] to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/null" produced an invalid new value for
.triggers["values"]: was
cty.StringVal("{\"controller\":{\"config\":{\"server-snippet\":\"listen
8000;\\nif ( $server_port = 80 ) {\\n  return 308
https://$host$request_uri;\\n}\\n\",\"ssl-redirect\":\"false\"},\"containerPort\":{\"http\":80,\"https\":443,\"special\":8000},\"service\":{\"annotations\":{\"service.beta.kubernetes.io/aws-load-balancer-backend-protocol\":\"tcp\",\"service.beta.kubernetes.io/aws-load-balancer-ssl-cert\":\"arn:aws:acm:eu-west-1:<redacted>\",\"service.beta.kubernetes.io/aws-load-balancer-ssl-ports\":\"443\",\"service.beta.kubernetes.io/aws-load-balancer-type\":\"nlb\"},\"targetPorts\":{\"http\":\"http\",\"https\":\"special\"}}}}"),
but now cty.StringVal("{\"controller\":{\"config\":{\"http-snippet\":\"server
{\\n  listen 2443;\\n  return 308
https://$host$request_uri;\\n}\\n\",\"proxy-real-ip-cidr\":\"<redacted>\",\"ssl-redirect\":\"false\",\"use-forwarded-headers\":\"true\"},\"containerPort\":{\"http\":80,\"https\":443,\"tohttps\":2443},\"extraArgs\":{\"disable-catch-all\":null},\"service\":{\"annotations\":{\"service.beta.kubernetes.io/aws-load-balancer-backend-protocol\":\"http\",\"service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout\":\"60\",\"service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled\":\"true\",\"service.beta.kubernetes.io/aws-load-balancer-ssl-cert\":\"arn:aws:acm:eu-west-1:<redacted>\",\"service.beta.kubernetes.io/aws-load-balancer-ssl-ports\":\"https\",\"service.beta.kubernetes.io/aws-load-balancer-type\":\"nlb\"},\"externalTrafficPolicy\":\"Local\",\"targetPorts\":{\"http\":\"tohttps\",\"https\":\"http\"},\"type\":\"LoadBalancer\"}}}").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for module.cluster.null_resource.wait_for_elb[0] to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/null" produced an invalid new value for
.triggers["version"]: was cty.StringVal("1.39.0"), but now
cty.StringVal("1.41.2").
```

As the output shows both the `values` and `version` fields were changed in the Helm resource. Yet, it is not clear to me why this leads to the experienced failure. Re-running terraform seems to solve the issue (provided no more changes are made to the Helm resource). But, I believe no error should happen in the first place.

**Comment by oniice** [comment] 2020-08-28 08:45
Also getting a very similar issue, with `null_resource` not being able to run and failing the build

@betabandido  Managed to get around it by adding a lifecycle rule to the `null_resource`

```
lifecycle {
    create_before_destroy = true
}
```

**Comment by IMKnysh** [comment] 2020-10-14 12:02
Faced with the same error :

Error: Provider produced inconsistent final plan

When expanding the plan for
module.alb_obfuscated_health_metric_monitor.null_resource.lb_monitor to
include new values learned so far during apply, provider
"registry.terraform.io/-/null" produced an invalid new value for
.triggers["target_group_arns"]: was cty.StringVal(""), but now
cty.StringVal("arn:aws:elasticloadbalancing:us-east-1:xxxxxxx:targetgroup/haproxy-int-dev-marlin-1-obf/a697bcfbfa677fb3").

In the plan I have:

module.alb_obfuscated_health_metric_monitor.null_resource.lb_monitor must be replaced
-/+ resource "null_resource" "lb_monitor" {
      ~ id       = "6071311259868463384" -> (known after apply)
      ~ triggers = { # forces replacement
          ~ "target_group_arns" = "arn:aws:elasticloadbalancing:us-east-1:xxxxxxxxx:targetgroup/haproxy-int-dev-marlin-1-obf/a697bcfbfa677fb3" -> ""
        }
    }

**Comment by kmoe** [comment] 2020-11-05 17:10
I haven't been able to reproduce this but am continuing to investigate. It looks like it could be related to https://github.com/hashicorp/terraform-provider-helm/issues/476, or a number of recently closed Core issues.

@betabandido Please try again with the latest version of this provider, and the latest version of Terraform 0.13 (and 0.14 if you can). Also please confirm whether this error occurs with `terraform plan`, or only `terraform apply`, and whether you can reproduce it without preexisting state.

@oniice and @IMKnysh Are you also using `helm_release`? Please post a reproduction case with minimal config.

**Comment by alewando** [comment] 2020-11-25 18:17
I'm experiencing this issue also, with Terraform 0.13.5 (and provider hashicorp/null v3.0.0). Reverting to TF 0.12 (with the same 3.0.0 provider) got it working again. 

I was able to reproduce it using the [attached](https://github.com/hashicorp/terraform-provider-null/files/5598498/issue-45-recreate.zip) relatively simple configuration.

Run it once with:
```terraform apply -auto-approve -var 'test_var=["a","b"]'```
And then run it again, removing an item from the list:
```terraform apply -auto-approve -var 'test_var=["a"]'```

Result: 
```Error: Provider produced inconsistent final plan

When expanding the plan for null_resource.test_resource to include new values
learned so far during apply, provider "registry.terraform.io/hashicorp/null"
produced an invalid new value for .triggers["role_ids"]: was
cty.StringVal("0UMqsckfSyAb5xbE"), but now
cty.StringVal("0UMqsckfSyAb5xbE,eXe8eMqVCKdUHcKJ").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

It seems to have something to do with the `create_before_destroy` lifecycle on the referenced resource. If I remove that, then it completes successfully. 

May be related to https://github.com/hashicorp/terraform/issues/25631 , but TF 0.13.5 was released _after_ that issue was closed and I'm still getting the error.

**Comment by nsvijay04b1** [comment] 2021-04-02 10:16
Same error. even create_before_destroy  doesnot help in my case.

**_PLAN_**

```
  - resource "null_resource" "triggers_run" {
      - id       = "6193030411763773835" -> null
      - triggers = {
          - "file" = "4e6d4c2c6406e7358a021e838260b847"
        } -> null
    }
```

**_ERROR_**

```
 provider
"registry.terraform.io/hashicorp/null" produced an invalid new value for
.triggers["file"]: was cty.StringVal("b1946ac92492d2347c6235b4d2611184"), but
now cty.StringVal("4e6d4c2c6406e7358a021e838260b847").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

```

**_CODE_**
I am generating a var file in resource  *triggers_init*  and i want to execute something( call ansible )  in resource *triggers_run* based on changes on if any file changes in resource  *triggers_init*

Since the file must be checkedin with in the module , lets say it is always empty  in the source control and resource  *triggers_init* adds content to it.  

```
resource "null_resource" "triggers_init" {
	triggers = {
	  version = timestamp()
	}
	provisioner "local-exec" {
	 command = <<EOT
	   echo "hello" > local-exec-init
	   echo "world" >> local-exec-init
	 EOT
	}
	lifecycle {
    create_before_destroy = true
    }
}
```

when i run download again from GIT (now file is again empty -but prev run it had content in it) , it fails  at  hashicorp/null provider .

```
resource "null_resource" "triggers_run" {
	depends_on = [null_resource.triggers_init]
	triggers = {
	  file = md5(file("${path.module}/local-exec-init"))
	}
	provisioner "local-exec" {
	 command = <<EOT
	 cat local-exec-init > local-exec-run
	 EOT
	}
	lifecycle {
    create_before_destroy = true
    }

}
```

**Comment by TJM** [comment] 2021-07-29 17:05
Our case is very similar to the top one, trying to install SOMETHING via helm_release, and having to use a "null_resource" to wait on the VIP to properly provision. If I change anything in the helm chart (such as the version), we want to run the null_resource.wait_on_vip provisioner (script) to wait for that service to be fully available to the Internet before continuing.

I am thinking that it happens when the "trigger" value changes during the "apply" phase of the run, but was not being changed during plan or maybe the plan didn't think it would change? So, steps to reproduce would be to first apply the code, then change the version or something in values, then plan/and apply the plan again. 

~tommy

**Comment by bflad** [comment] 2023-03-08 21:14
Hi folks 👋  Off the top of my head, there can be two classes of issues which could cause this.

The first being `null_resource` references to _other_ resource attributes where those resources do not properly signal to Terraform during planning that an in-place update will cause that attribute's value to change (either to unknown, or a known new value). This will always require a fix in the source resource.

The second is where Terraform function calls, such as `md5()`, do not participate in the dependency graph. Therefore the result of the function may only be based on prior state values except on creation where it should be marked as unknown. This timing aspect is alluded to in the [`file()` function](https://developer.hashicorp.com/terraform/language/functions/file) documentation:

> This function can be used only with files that already exist on disk at the beginning of a Terraform run. Functions do not participate in the dependency graph, so this function cannot be used with files that are generated dynamically during a Terraform operation.

However it may be worth [creating an issue in the Terraform core issue tracker](https://github.com/hashicorp/terraform/issues/new/choose) to also document the timing implementation details for the hashing functions as well in the case of a configuration value such as `md5(join(" ", aws_s3_object.content.*.etag))`.

To get something that properly participates in the graph to generate a hash, it would need to be its own resource or data source. There may be community providers that accomplish this already.

**Comment by bflad** [comment] 2023-03-09 14:45
Apologies for the extra noise, I meant to write this additional content yesterday.

The `null_resource` managed resource `triggers` attribute itself does not perform any manipulation of planned data when writing applied data, so any `Provider produced inconsistent final plan` would likely be generated from either of the two cases above. Therefore, since there is nothing to be done in _this_ codebase, I'm going to close this issue.

You can sometimes catch other providers written with terraform-plugin-sdk that are incorrectly not implementing plans by enabling WARN logging in Terraform, e.g. `TF_LOG=WARN terraform apply`, and looking for Terraform core log lines containing:

```
Provider "..." produced an unexpected new value for ..., but we are tolerating it because it is using the legacy plugin SDK.
The following problems may be the cause of any confusing errors from downstream operations:
```

Any of those issues should be raised in the source provider.

**Closed by bflad** 2023-03-09 14:45 UTC
