### ISSUE TITLE
null_resource triggers unneccessary replace

### ISSUE THREAD

**Issue by AmineChikhaoui** [hashicorp/terraform-provider-null#162] opened 2022-11-17 21:53 UTC
### Terraform CLI and Provider Versions

```
❯ terraform version
Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/null v3.2.0
```

### Terraform Configuration

```terraform
resource "null_resource" "create_zip_every_time" {
  triggers = {
    always_run = timestamp()
  }
}

data "archive_file" "bundle" {
  type = "zip"

  output_path = "/tmp/foo.zip"
  depends_on  = [null_resource.create_zip_every_time]

  source {
    filename = "foo.txt"
    content  = "foo"
  }
}

resource "null_resource" "dependent" {
  triggers = {
    checksum = data.archive_file.bundle.output_md5
  }
}

output "checksum" {
  value = data.archive_file.bundle.output_md5
}
```

### Expected Behavior

I know the config is a bit weird but I'm just trying to show a minimal reproduce.
As you can see in the config, eventhough `archive_file` is forced to be created each time, the checksum never actually changes as it's the same content over and over.  But with this config, the `null_resource.dependent` resource keeps getting deleted and recreated unnecessarily while I expected it should be a no-op since the value of the checksum is exactly the same at the end.

### Actual Behavior

The `null_resource.dependent` keeps getting deleted and created again
```
Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
-/+ destroy and then create replacement
 <= read (data resources)

Terraform will perform the following actions:

  # data.archive_file.bundle will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "archive_file" "bundle" {
      + id                  = (known after apply)
      + output_base64sha256 = (known after apply)
      + output_md5          = (known after apply)
      + output_path         = "/tmp/foo.zip"
      + output_sha          = (known after apply)
      + output_size         = (known after apply)
      + type                = "zip"

      + source {
          + content  = "foo"
          + filename = "foo.txt"
        }
    }

  # null_resource.create_zip_every_time must be replaced
-/+ resource "null_resource" "create_zip_every_time" {
      ~ id       = "5577006791947779410" -> (known after apply)
      ~ triggers = { # forces replacement
          ~ "always_run" = "2022-11-17T21:46:19Z" -> (known after apply)
        }
    }

  # null_resource.dependent must be replaced
-/+ resource "null_resource" "dependent" {
      ~ id       = "8674665223082153551" -> (known after apply)
      ~ triggers = { # forces replacement
          ~ "checksum" = "65681cd4d9d55e9eb423edba41dca393" -> (known after apply)
        }
    }

Plan: 2 to add, 0 to change, 2 to destroy.

Changes to Outputs:
  ~ checksum = "65681cd4d9d55e9eb423edba41dca393" -> (known after apply)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

null_resource.dependent: Destroying... [id=8674665223082153551]
null_resource.dependent: Destruction complete after 0s
null_resource.create_zip_every_time: Destroying... [id=5577006791947779410]
null_resource.create_zip_every_time: Destruction complete after 0s
null_resource.create_zip_every_time: Creating...
null_resource.create_zip_every_time: Creation complete after 0s [id=5577006791947779410]
data.archive_file.bundle: Reading...
data.archive_file.bundle: Read complete after 0s [id=6af8b2a5aa15493d28dc45d2009e35b1d8238294]
null_resource.dependent: Creating...
null_resource.dependent: Creation complete after 0s [id=8674665223082153551]

Apply complete! Resources: 2 added, 0 changed, 2 destroyed.

Outputs:

checksum = "65681cd4d9d55e9eb423edba41dca393"
```

### Steps to Reproduce

`terraform apply`

### How much impact is this issue causing?

Medium

### Logs

https://gist.github.com/AmineChikhaoui/c656044fcbd04c1516164c8fc271af59

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SBGoods** [comment] 2022-11-23 20:43
Hi @AmineChikhaoui,

From what I can see in your example configuration, this is expected behavior from Terraform and the Null Provider. The use of `depends_on` in the "bundle" data source causes the data source to be read during the apply phase instead of during the plan phase. Because of this, the value of `data.archive_file.bundle.output_md5` in the plan is `Unknown`  instead of the checksum value which is causing the replacement of the "dependent" resource.

The `depends_on` argument typically causes Terraform to mark more resources for replacement than necessary. There is likely other ways to accomplish what you are trying to achieve but it is hard to give suggestions without seeing your actual configuration. We can try to give more guidance if you can provide some more context in our [discuss forums](https://discuss.hashicorp.com/c/terraform-providers/31).

I'm closing this issue here, but please feel free to reach out if you have any further questions!

**Closed by SBGoods** 2022-11-23 20:43 UTC
Labels: bug
